### PR TITLE
Rework the computation of the addresses that functions are loaded at for LLVM 3.8.

### PR DESCRIPTION
**Pull request by JSStats**
Need these changes for LLVM 3.8. Seeing if there is any chance these are compatible with 3.7, or how to handle this.

### CODE REVIEW

**Comment by JSStats** [comment]
Not ready to merge. Shall have to look into how the llvm versions differences are to be handled?

**Comment by JSStats** [comment]
Looks ready to review now.

**Comment by AndrewScheidecker** [comment]
Sorry, I don't think it's worth the mess to support multiple versions of LLVM simultaneously. I recommend that you use LLVM 3.7 with WAVM. I'll switch to LLVM 3.8 once it's released.

**Comment by icefox** [comment]
@AndrewScheidecker Now that LLVM 3.8.0 has been out for a while (and 3.8.1 is about to be released) did you want to move to 3.8?

**Comment by AndrewScheidecker** [comment]
As of 771a610bb8669912a35aa15e2e0b1593b8c1fd4a, WAVM is now using LLVM 3.8.

**Pull request closed without merging**
