### PR TITLE
Define Emscripten syscall146 for writev, and a few other stubs.

### PR DESCRIPTION
**Pull request by JSStats**
This was enough to get the zlib benchmark working, still lots to do.

### CODE REVIEW

**Comment by AndrewScheidecker** [comment]
Can you make this portable? AFAICT there isn't a Windows equivalent to writev, though.

**Comment by JSStats** [comment]
An attempt has been made to get this working on Windows, but it is not tested. Can you take it from here?

**Comment by AndrewScheidecker** [comment]
Sure, although just from looking at it I think you need to wrap the `#include` in an `#ifdef`. Can you also add the zlib benchmark to the Test folder, or something else that calls it?

**Comment by JSStats** [comment]
Fixed the include, added the zlib benchmark. ptal

**Comment by AndrewScheidecker** [comment]
Looks good, thanks! I added bounds checking for the buffers, and made it use vmFile so whenever that works the fd parameter will work.

**Pull request merged**
