### PR TITLE
Output information about errors during SExp::parse

### PR DESCRIPTION
**Pull request by icefox**

### CODE REVIEW

**Comment by icefox** [comment]
I ran across this particular edge case when trying to run some was that had a function that had :: in the name.  Getting late and wasn't able to track down the bug, but at least with this change it will output a helpful error message

Checking on https://github.com/WebAssembly/spec/tree/master/ml-proto : is allowed in names.
name: (<letter> | <digit> | _ | . | + | - | * | / | \ | ^ | ~ | = | < | > | ! | ? | @ | # | $ | % | & | | | : | ' | `)+


```
./bin/Run -text fail.wast m
Error parsing WebAssembly text file:
fail.wast:expected ')' following S-expression child nodes but found '('
(module (fund a::b))
               ^
```

**Comment by icefox** [comment]
From the build failures this also exposed some parsing failures that were hiding.

**Comment by AndrewScheidecker** [comment]
f1184f011931e4da0df14c9c941e3ccf7db3107d should fix your problem with name syntax.

**Comment by icefox** [comment]
Still seeing the syntax error

`$ ./bin/wavm bad2.wast 
Error parsing WebAssembly text file:
bad2.wast:1:16: expected ')' following S-expression child nodes but found ':'
(module (func a::b))
               ^
`

**Comment by AndrewScheidecker** [comment]
I missed this in your original post: names must start with a $.

**Comment by icefox** [comment]
Ah yeah the original code I was testing before it was stripped down had the $ and that works now

(func $wasm::print_i32 (type $rustfn-0-31) (param $0 i32)

**Pull request merged**
