### PR TITLE
Fix uint64 printing.

### PR DESCRIPTION
**Pull request by JSStats**
Fixes compilation failures on 32 bit and 64 bit linux. Any chance this also works on Windows?

### CODE REVIEW

**Comment by JSStats** [comment]
Build system does not appear to define PRIx64 so that does not help too much!

**Comment by AndrewScheidecker** [comment]
I think this has problems on Windows, actually, since "long int" is only 32-bits. I'm going to just rewrite it to not use sprintf.

**Comment by AndrewScheidecker** [comment]
Can you try the commit I just pushed?

**Comment by JSStats** [comment]
Yes, fixed, thanks.

**Pull request closed without merging**
